JOBS_FOLDER = "C:\\Users\\kaminoshinyu\\Desktop\\jobs"
HTML_HEADING = "DocTa"
VERSION = "v1.9"
PERSIST_JOBS = False
HOST = "0.0.0.0"
DEBUG_SERVER = False
PATH_DEPENDENCIES = ["pandoc", "latex", "tex"]
PATH_DEPENDENCIES_LINUX = ["pandoc", "tidy", "texlive-latex-base", "texlive-binaries"]
PYTHON_PACKAGES = ["flask", "flask_cors", "pypandoc", "tidylib", "bs4", "PIL", "sympy"]
PYTHON_VERSION_MIN = "3.4"
