JOBS_FOLDER = "C:\\Users\\kaminoshinyu\\Desktop\\jobs"
HTML_HEADING = "DocTa"
VERSION = "v2.0"
PERSIST_JOBS = False
HOST = "0.0.0.0"
DEBUG_SERVER = False
PATH_DEPENDENCIES = ["pandoc", "latex", "tex"]
PYTHON_PACKAGES = ["flask", "flask_cors", "pypandoc", "tidylib", "bs4", "PIL", "sympy"]
PYTHON_VERSION_MIN = "3.4"
